### ISSUE TITLE
Bazarr not themed

### ISSUE THREAD

**Issue by kantjer** [GilbN/theme.park#184]
**Describe the bug**
I tried a few Bazarr css scripts is Stylus but none of them do anything. Sonarr and Radarr for example work fine.
**To Reproduce**
1. Add script to stylus as described in the WiKi
2. Bazarr is not themed at all

**Expected behavior**
Bazarr to be themed like Sonarr and Radarr

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser chrome
 - Version 90.0.4430.85 (Official Build) (64-bit)

**Additional context**
I tried the following themes: Dark, Space Gray and Organizr Dark. None of them work on Bazarr v.3.0.2.4552

**Comment by GilbN** [comment]
Looks like I pulled the trigger on the new Bazarr react frontend a bit early. The theme work on the Bazarr development branch. 

The old base css is here if you want to use that with the Stylus plugin ect 
https://github.com/GilbN/theme.park/blob/master/CSS/themes/bazarr/bazarr-base-old.css

**Comment by kantjer** [comment]
Thanks, how do I use that to set the organizr-dark theme in Stylus?
Just copy it in Stylus doesn't give me a workable theme.

**Comment by GilbN** [comment]
> Thanks, how do I use that to set the organizr-dark theme in Stylus?
> Just copy it in Stylus doesn't give me a workable theme.

```css
@import "https://gilbn.github.io/theme.park/CSS/themes/bazarr/bazarr-base-old.css";
:root {
  --main-bg-color: #1f1f1f;
  --modal-bg-color: #1b1b1b;

  --button-color: #2cabe3;
  --button-color-hover: rgb(44 171 227 / .8);
  --accent-color:  #2cabe3;
  --accent-color-hover: white;
}
```
