### ISSUE TITLE
Theme not working for newest radarr (3.1.1.4954-ls103)

### ISSUE THREAD

**Issue by mcpowell87** [GilbN/theme.park#190]
**Describe the bug**
Just pulled the newest linuxserver docker image for Radarr (3.1.1.4954-ls103) and both the theme and 4k logo stopped working, and it is showing the default Radarr theming now.  I don't see any errors in the dev console or in the docker container logs.  I do see they slightly modified some styling, but it's so minor I'm not sure if that could really affect it.  I am using the Plex theme, but I tried others also and I get the same result.  

Any ideas?

**Comment by solongandthxforallthefish** [comment]
same here, theme.park stopped working in newest radarr release

**Comment by GilbN** [comment]
I'm not seeing this, I'm on the same version. Need more info. Please fill out the issue template.

**Comment by stefanelul2000** [comment]
I'm running 3.1.1.4954 (latest version as of now) and the themes load without any issues.

**Comment by IntermittentlyRupert** [comment]
I recently had to update the `DOCKER_MODS` environment variable from `gilbn/theme.park:<app>` to `ghcr.io/gilbn/theme.park:<app>` to fix this issue (for me it affected all containers using Docker mods). The GHCR URL is the version [now given in the docs](https://docs.theme-park.dev/setup/#enviroment-variables), but the Docker Hub version used to work fine as well.

Looking at the container logs when using the old URL, I see:

```
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

...so it seems to not be pulling the mod correctly.

There might be an issue with the version deployed to Docker Hub, or maybe we're just running into rate limits? (Or something completely different that I haven't thought of.)

**Comment by solongandthxforallthefish** [comment]
**Describe the bug**
thema park theme is not working since radarr Version 3.1.1.4954

**To Reproduce**
updated to Version 3.1.1.4954

**Expected behavior**
show the theme

**Theme Install Method**
Docker compose

```
version: '2.1'
services:
 radarr:
    image: ghcr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
        - PUID=1000
        - PGID=100
        - TZ=Europe/Amsterdam
        - DOCKER_MODS=gilbn/theme.park:radarr
        - TP_THEME=aquamarine
    volumes:
        - xxx:xxx
        - xxx:xxx
    ports:
        - 7878:7878
    restart: unless-stopped
```
