### ISSUE TITLE
Sonarr label default/inverse same color

### ISSUE THREAD

**Issue by Shadow58624** [GilbN/theme.park#192]
**Describe the bug**
Each episode row in a show has a rectangle in the status column which specifies the quality and resolution of the file and has a different color based on if the file has reached the desired quality of the current quality profile. At the moment they both have the same color which makes it difficult to find the episodes which have not met the wanted quality.

**To Reproduce**
1. Go to any show
2. Click on a season
3. Scroll down to any episode
4. See colors of episodes that reached the quality desired and the ones that haven't

**Expected behavior**
A lighter color for episodes that have not yet matched the quality profile cut-off.

**Screenshots**
Before (blue has reached quality, white hasn't)
![image](https://user-images.githubusercontent.com/29847057/117320300-00f67500-ae84-11eb-927d-536b3f1a5147.png)
After
![image](https://user-images.githubusercontent.com/29847057/117320372-14a1db80-ae84-11eb-809e-c7f751ce8787.png)

The problem seems to be in `sonarr-base.css` at:
```
[class*="Label\/default\/"],
[class*="Label\/inverse\/"] {
    border-color: var(--accent-color);
    background-color: var(--accent-color);
    color: #fff;
}
```

**Comment by GilbN** [comment]
Makes sense 👍

**Comment by Shadow58624** [comment]
I don't know if the same happens in the other *arrs, haven't checked

**Comment by GilbN** [comment]
It does, so I have to fix them too. Need to remove the label inverse class from all the bases.

**Comment by GilbN** [comment]
Or you can make a PR :P

**Comment by Shadow58624** [comment]
I would love to but I have no clue how to do those things and am always afraid to mess it up.

**Comment by GilbN** [comment]
Perfect time to learn :) Spend 30m-1h on youtube and you're all set. And you can't really mess anything up, if its wrong I wont accept the PR and I'll just tell you what you need to do to fix it ;)

**Comment by Shadow58624** [comment]
So, I've pulled the repo. Should I make a branch to make the changes or do I make them in master?

**Comment by GilbN** [comment]
> So, I've pulled the repo. Should I make a branch to make the changes or do I make them in master?

You can make a new branch

**Comment by Shadow58624** [comment]
Another question, for testing I've been using stylus and changing the values there, and then copying them into vscode. Is there a way to test the changes more optimally?

**Comment by GilbN** [comment]
I use stylus a lot actually, that and just editing the style directly in the browser. You can host the css using a webserver and add it with stylus that way, with the @import line 

```css
@import url("https://mydomain.com/theme.park/CSS/themes/sonarr/sonarr-base.css")
:root {
  --main-bg-color: #1f1f1f;
  --modal-bg-color: #1b1b1b;

  --calendar-tv-unaired-premiere: 53 197 244;
  --calendar-tv-downloading: 122 67 182; 
  --calendar-tv-unmonitored: 173 173 173;
  --calendar-tv-unaired: 93 156 236;  
  --calendar-tv-missing: 240 80 80;
  --calendar-tv-on-air: 255 165 0; 
  --calendar-tv-available: 39 194 76;
  
  --button-color: #2cabe3;
  --button-color-hover: rgb(44 171 227 / .8);
  --button-text: #eee;
  --button-text-hover: #fff;

  --accent-color:  #2cabe3;
  --accent-color-hover: white;
  --queue-color: #2cabe3;
  --link-color: #2cabe3;
  --link-color-hover: #fff;
    
  --text:#96a2b4;
  --text-hover: #fff;
  --text-muted: #999;
  }
```
