### ISSUE TITLE
Sonarr theme fails to appy

### ISSUE THREAD

**Issue by tordenflesk** [GilbN/theme.park#199]
**Describe the bug**

[mod-init] Applying gilbn/theme.park:sonarr files to container,
gzip: stdin: not in gzip format,
tar: Child returned status 1,
tar: Error is not recoverable: exiting now

**Theme Install Method** (Don't skip)
```
---
version: "2.1"
services:
  sonarr:
    image: ghcr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/Oslo
      - DOCKER_MODS=gilbn/theme.park:sonarr
      - TP_THEME=space-gray
    volumes:
      - /srv/dev-disk-by-label-DATA01/Docker_Config/SONARR:/config
      - /srv/dev-disk-by-label-DATA00:/DATA00
      - /srv/dev-disk-by-label-DATA01:/DATA01
    network_mode: host
    restart: unless-stopped

```
**Application Info** (Don't skip)
- Sonarr / Latest
