### ISSUE TITLE
OMBI V4 dark theme not working at all

### ISSUE THREAD

**Issue by mkanet** [GilbN/theme.park#206]
**Describe the bug**
It appears the OMBI dark theme was meant for the old version of OMBI.  The theme colors look exactly the same after adding the subfilter.  Instead of a dark color theme similar to Petio, it's still the default ugly dark blue theme.   I tried using Petio's CSS; but, that didn't help much.

This should be very easy to reproduce.

**Theme Install Method** (Don't skip)
nginx subfilter:
**https://theme-park.dev/CSS/themes/ombi/organizr-dark.css**

![image](https://user-images.githubusercontent.com/811008/121109603-c48aa180-c7c0-11eb-928c-ce9af2beee08.png)

**Comment by Lanjelin** [comment]
The Ombi theme is for V3 afaik, and has not yet been updated for V4.
Ombi supports custom css through Settings -> Configuration -> Customization, and you can paste the CSS directly there.
Just made some quick and dirty style, until someone more skilled comes around and does it properly.
Plex-theme background, with white text.

```css
/* Removing Application Name at top left */
#nav-applicationName{display:none;}

/* Visibility */
.top-search-block, .mat-flat-button, .mat-mini-fab, .mat-raised-button {color:white !important;}
.top-search-bar .mat-form-field-flex, .discover-filter-buttons-group{border: 1px solid white !important;}

/* Plex Background */
body, .discover-filter-buttons-group, .card-top-info, .mat-table, .mat-paginator, .sidenav-container, .mat-menu-panel, .mat-fab.mat-accent, .mat-flat-button, .mat-mini-fab, .mat-raised-button, .sidenav, .content-container, .top-bar-container {background: url("https://raw.githubusercontent.com/gilbN/theme.park/master/Resources/preset-dark2.png") center center/cover no-repeat fixed !important; }
```

**Comment by mkanet** [comment]
Thank you so much for the quick and very help response.  It is significantly better.  There's only a weird issue... the status for each TV/movie is not displaying correctly.  Any idea how I might be able to resolve that?  Otherwise, it's very nice.

**Original:**  (correct)
![Screenshot 06-08-2021 at 09 43 46 AM](https://user-images.githubusercontent.com/811008/121225414-597fb000-c83e-11eb-9ba2-f942ecee3ca7.png)

**CSS-Mod:**  (status not displayed correctly)
![Dark](https://user-images.githubusercontent.com/811008/121225543-787e4200-c83e-11eb-89cd-a497e2031a40.png)

**Comment by Lanjelin** [comment]
The black overlay was not positioned perfectly after changing the background of the whole box, so I changed the overlay as well. Seems it broke it though. 
Unable to find a quick way to fix the position, but I guess a few pixels off is better then broken.
Updated my previous post, and removed `.card-top-info` from background.

**Comment by mkanet** [comment]
@Lanjelin thank you so much for taking the time to do this.  I was able to find the specific css element and properties to adjust `.card-top-info` using Chrome Developer tools.  However, just pasting the below code in OMBI's CSS customization gets ignored.

Any ideas why the CSS code below works in Developer Mode; but, not when adding it to OMBI's CSS customization?

```
.card-top-info[_ngcontent-nhx-c214] {
    position: absolute;
    top: 5px;
    width: 100%;
    background-color: rgba(15,23,31,.7);
    display: flex;
    justify-content: space-between;
    padding-top: 4.6px;
    padding-bottom: 6.3px;
    z-index: 2;
    letter-spacing: .2px;
}
```

**Comment by Lanjelin** [comment]
Use `!important` to override already defined properties. https://www.w3schools.com/css/css_important.asp
```css
.card-top-info {
    top: 5px !important;
    padding-top: 4.6px !important;
    padding-bottom: 6.3px !important;
}
```
