### ISSUE TITLE
This is a PR friendly repo! :bulb:

### ISSUE THREAD

**Issue by GilbN** [GilbN/theme.park#208]
If you want to contribute. PR's on existing themes, new theme colors and or applications are more than welcome! 

There aren't really any contribution guidelines, but I would ask for that the theme would have at a minimum these variables:

```css
  --main-bg-color: #abcdef;
  --modal-bg-color: #abcdef;

  --button-color: #abcdef;
  --button-color-hover: #abcdef;
  --button-text: #abcdef;
  --button-text-hover: #abcdef;

  --accent-color:  nnn,nnn,nnn; /* Example .class { color: rgb(var(--accent-color)) } */
  --accent-color-hover: #abcdef;
 
  --link-color: #abcdef;
  --link-color-hover: #abcdef;
    
  --text:#abcdef;
  --text-hover: #abcdef;
  --text-muted: #abcdef;
  ```

If you have any questions come chat in my [Discord](https://docs.theme-park.dev/discord)!
