### ISSUE TITLE
Readarr "No such file or directory" errors and themes not applied

### ISSUE THREAD

**Issue by rocketfuelindustries** [GilbN/theme.park#236]
**Describe the bug**
Errors running theme for hotio Readarr container. Resulting site is not themed.
From the logs:

```
[cont-init.d] 99-themepark: executing... 
---------------------------
|  Readarr theme.park Mod  |
---------------------------
Variables set:
'TP_DOMAIN'=
'TP_THEME'=organizr-dark

No domain set, defaulting to theme-park.dev
grep: /app/readarr/bin/UI/index.html: No such file or directory
---------------------------
|  Adding the stylesheet  |
---------------------------
sed: can't read /app/readarr/bin/UI/index.html: No such file or directory
sed: can't read /app/readarr/bin/UI/login.html: No such file or directory
Stylesheet set to organizr-dark
    
[cont-init.d] 99-themepark: exited 0.
```
**Theme Install Method** (Don't skip)
- docker-compose install - relevant lines:
```
    image: hotio/readarr:nightly
    volumes:
    - $DOCKERDIR/readarr/98-themepark:/etc/cont-init.d/99-themepark
    environment:
    - TP_HOTIO="true"
    - TP_THEME=organizr-dark
```

**Application Info** (Don't skip)
- Version
0.1.0.896
Package Version - nightly-3d52e12 by hotio
- Container
  hotio/readarr:nightly
- Theme version
  latest downloaded from github 30 minutes ago. I don't know how to tell the version number.

**To Reproduce**
do the stuff above, then run

**Expected behavior**
Theme applied without errors
