### ISSUE TITLE
Organizr Glass don't work since 1.6.0

### ISSUE THREAD

**Issue by fana13** [GilbN/theme.park#281]
**Describe the bug**
The URL https://theme-park.dev/css/base/organizr/organizr-base-old.css don't work since last update.
There's a 404 error 

**Theme Install Method** (Don't skip) : custom CSS in Organizr

**Application Info** (Don't skip)
- Version 1.6.0
- Branch Default

**Comment by GilbN** [comment]
Organizr glass is deprecated

**Comment by GilbN** [comment]
https://github.com/GilbN/theme.park/blob/9fedde26fa2749e5c291cc647714eb5a86d3dd01/css/base/organizr/organizr-base-old.css you can paste this

**Comment by fana13** [comment]
Thank you @GilbN  but this link don't work like this if i paste it with this syntax :
`@import "https://github.com/GilbN/theme.park/blob/9fedde26fa2749e5c291cc647714eb5a86d3dd01/css/base/organizr/organizr-base-old.css"; 
`
This Organizr Glass is really an amazing theme, many thanks for your hard work !

**Comment by GilbN** [comment]
Link won't work. Just the content

**Comment by fana13** [comment]
Sorry, i'm not very good.
I don't know how use it in CSS custom with Organizr.

**Comment by GilbN** [comment]
Just copy paste the content

**Comment by fana13** [comment]
Unfortunately it doesn't work neither

**Comment by GilbN** [comment]
Copy from the raw link

**Comment by fana13** [comment]
Glad it's working, thanks for your patience

**Comment by fana13** [comment]
Links https://theme-park.dev/css/base/organizr/organizr-base-old.css and https://theme-park.dev/CSS/themes/organizr/organizr-base-old.css still offline yet

**Comment by GilbN** [comment]
Haven't merged develop yet. Use https://develop.theme-park.dev/css/addons/organizr/glass/organizr-base-old.css.css

**Comment by fana13** [comment]
Hello,

Since this morning the glass base doesn't seem to work.
I use both https://develop.theme-park.dev/css/addons/organizr/glass/organizr-base-old.css and https://theme-park.dev/css/addons/organizr/glass/glass-base.css.
I know the full version has been deprecated, but have you did a modification ? Or the issue is on my own config ?
Thanks a lot.

**Comment by GilbN** [comment]
> Hello,
> 
> Since this morning the glass base doesn't seem to work. I use both https://develop.theme-park.dev/css/addons/organizr/glass/organizr-base-old.css and https://theme-park.dev/css/addons/organizr/glass/glass-base.css. I know the full version has been deprecated, but have you did a modification ? Or the issue is on my own config ? Thanks a lot.

Adding 
```css
@import "https://theme-park.dev/css/addons/organizr/glass/organizr-base-old.css"; 
@import "https://theme-park.dev/css/addons/organizr/glass/glass-base.css"; 
:root {
    --main-bg-color: url(https://theme-park.dev/css/addons/organizr/glass/example.jpg) center center/cover no-repeat fixed;
    --mobile-bg-color: radial-gradient(circle, #3a3a3a, #2d2d2d, #202020, #141414, #000000) center center/cover no-repeat fixed;

    --link-color: #fff;
    --custom-buttons-color: radial-gradient(ellipse at center, #3F51B5 0%, #009688 100%) center center/cover no-repeat fixed;
    --hompage-item-hover: radial-gradient(ellipse at center, rgba(0, 150, 136, 0.33) 0%, #b53f3f73 100%) center center/cover no-repeat fixed;
    --notification-box-line: #000;

    --div-background-color-10: rgba(0, 0, 0, 0.15);
    --div-background-color-15: rgba(0, 0, 0, 0.25);
    --div-background-color-25: rgba(0, 0, 0, 0.35);
    --div-background-color-35: rgba(0, 0, 0, 0.45);
}
```
looks to be working here
