### ISSUE TITLE
Deluge Won't Start

### ISSUE THREAD

**Issue by KillahB33** [GilbN/theme.park#369]
**Describe the bug**
Deluge seems to be stuck and not starting with TP added.
I assumed it had to do with Scheme but even after switching to http it still wasn't working.

**Theme Install Method** (Don't skip)
- Docker run / Compose Config
```yaml
  deluge:
    image: linuxserver/deluge
    container_name: deluge
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=timezone
      - UMASK_SET=022 #optional
      - DELUGE_LOGLEVEL=error #optional
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:deluge
      - TP_THEME=dark
      - TP_SCHEME=http
    volumes:
      - /opt/config/deluge:/config
      - /opt/downloads:/downloads
    restart: unless-stopped
```

**Application Info** (Don't skip)
Running latest on everything

**To Reproduce**
Using docker mod 

**Desktop (If applicable) (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu
 - Browser [e.g. chrome, safari] Brave

**Additional context**
