### ISSUE TITLE
qBittorrent theme only works for login page

### ISSUE THREAD

**Issue by pro4tlzz** [GilbN/theme.park#387]
**Describe the bug**
Not a biggy for me but recently noticed that the theme only loads for the login page and not for the other pages of qBittorrent

**Theme Install Method** (Don't skip)
- Docker run / Compose Config
```
      qbittorrent:
        container_name: qbittorrent
        network_mode: 'service:wireguard-client'
        depends_on: 
         - wireguard-client
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/London
            - UMASK_SET=022
            - WEBUI_PORT=8180
            - DOCKER_MODS=ghcr.io/gilbn/theme.park:qbittorrent
            - TP_THEME=organizr
        volumes:
            - '/media/HDDs/25TBR10/data:/data'
        restart: unless-stopped
        image: linuxserver/qbittorrent
```
docker logs
```
------------------------------

| qBittorrent theme.park Mod |

------------------------------

Variables set:

'APP_FILEPATH'=/config/qBittorrent/qBittorrent.conf

'TP_DISABLE_THEME'=

'TP_HOTIO'=

'TP_DOMAIN'=

'TP_COMMUNITY_THEME'=

'TP_SCHEME'=

'TP_THEME'=organizr


No domain set, defaulting to theme-park.dev

No scheme set, defaulting to https

---------------------------------------

| Adding the stylesheet to html files |

---------------------------------------

find: ./themepark/private: No such file or directory

cont-init: info: /etc/cont-init.d/98-themepark exited 0

cont-init: info: running /etc/cont-init.d/99-custom-files

[custom-init] no custom files found exiting...

cont-init: info: /etc/cont-init.d/99-custom-files exited 0

s6-rc: info: service legacy-cont-init successfully started

s6-rc: info: service legacy-services: starting

services-up: info: copying legacy longrun qbittorrent (no readiness notification)

s6-rc: info: service legacy-services successfully started

s6-rc: info: service 99-ci-service-check: starting

[ls.io-init] done.

s6-rc: info: service 99-ci-service-check successfully started
```
- Webserver subfilter Config
```
      location / {
      proxy_pass http://127.0.0.1:8180/;
      proxy_http_version 1.1;
      http2_push_preload on; # Enable http2 push
      proxy_set_header   Host               127.0.0.1:8180;
      proxy_set_header   X-Forwarded-Proto  $scheme;
      proxy_set_header   X-Forwarded-Host   $http_host;
      proxy_set_header   X-Forwarded-For    $remote_addr;
      proxy_set_header   X-Real-IP          $remote_addr;
      proxy_hide_header "x-webkit-csp";
      proxy_hide_header "content-security-policy";
      proxy_hide_header "X-Frame-Options";
      }
```

**Application Info** (Don't skip)
- Linux server qbittorrent version:  4.4.3.1-r1-ls204 Build-date:- 2022-06-17T10:27:46+02:00
- Branch: Latest

**To Reproduce**
1. Go to login page, see correct theme
![image](https://user-images.githubusercontent.com/22709115/174672462-1533b7cf-34fe-4677-8e7c-dd2bc0764bb2.png)

2. Login and no theme 
![image](https://user-images.githubusercontent.com/22709115/174672486-87a7573b-f869-4961-9137-fd07b94b40b0.png)

**Expected behavior**
Theme should show after login as well
**Screenshots**

**Desktop (If applicable) (please complete the following information):**
 - OS: Windows 10
 - Browser : Edge
 - Version  102.0.1245.44
 - nginx version: nginx/1.21.6

I should note that before this issue I did not have the 3 lines to hide the headers in my proxy, it worked fine without
