### ISSUE TITLE
Traefik?

### ISSUE THREAD

**Issue by Mbarmem** [GilbN/theme.park#42]
Hi,
Is their any way to install the theme via Traefik reverse proxy?

I am asking since i see guides for Apache and Caddy.

**Comment by gilbN** [comment]
Hi. Sorry I haven't found a way to the subfiltering with træfik yet. I would as the dvs if they have some similar function. I use the better web server..nginx :P

**Comment by gilbN** [comment]
@Mbarmem see if you can get this working https://pilot.traefik.io/plugins/270947800646156800/rewrite-body

**Comment by gilbN** [comment]
Note to self: Doesn't work with the current implementation of the traefik plugin. 
https://github.com/traefik/plugin-rewritebody/issues/12

**Comment by IntermittentlyRupert** [comment]
It seems that traefik/plugin-rewritebody#12 no longer causes issues with injecting styles. However traefik/plugin-rewritebody#13 causes the plugin to fail for some containers.

Of the containers I've tried, these work:
* `portainer/portainer`
* `plexinc/pms-docker`
* `linuxserver/jackett`
* `linuxserver/deluge`
* `linuxserver/nzbhydra2`

and these don't:
* `linuxserver/sonarr`
* `linuxserver/radarr`
* `linuxserver/sabnzbd`

Here's a minimal example for Portainer using the Docker config provider:
```yaml
version: "3"
services:
  traefik:
    image: traefik
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - --providers.docker=true
      - --pilot.token=${TOKEN}
      - --experimental.plugins.rewrite.modulename=github.com/traefik/plugin-rewritebody
      - --experimental.plugins.rewrite.version=v0.3.1
  portainer:
    image: portainer/portainer
    labels:
      - traefik.http.routers.portainer.rule=Host(`portainer.localhost`)
      - traefik.http.routers.portainer.middlewares=portainer
      - traefik.http.middlewares.portainer.plugin.rewrite.rewrites.regex=</head>
      - traefik.http.middlewares.portainer.plugin.rewrite.rewrites.replacement=<link rel="stylesheet" type="text/css" href="https://gilbn.github.io/theme.park/CSS/themes/portainer/${THEME}.css"></head>
```

**Comment by gilbN** [comment]
@IntermittentlyRupert btwm there are some docker mods you can now use to apply the themes with. (Only for linuxserver) https://github.com/gilbN/theme.park/wiki/Setup#docker-mods

**Comment by IntermittentlyRupert** [comment]
@gilbN Oh, that's awesome! Between the Docker mods and the Traefik rewrite plugin, the only app I use that I can't inject styles for is Organizr, and that supports custom CSS.

**Comment by gilbN** [comment]
> @gilbN Oh, that's awesome! Between the Docker mods and the Traefik rewrite plugin, the only app I use that I can't inject styles for is Organizr, and that supports custom CSS.

Yeah. I didnt crate any mods for apps that support custom css. And organizr has my themes in the marketplace too. 👍🏻

**Comment by beloso** [comment]
Sorry for highjacking this. But do you have a rewrite example for Qbittorrent?

I was able to get the themes to working with Stylus + Middleware for the headers needed to hide.
I'd like to keep it all within the Middleswares

I tried this one:
```
  middlewares:
    qbittheme:
      plugin:
        rewritebody:
          rewrites:
            regex: </noscript>
            replacement: <link rel='stylesheet' type='text/css' href='https://gilbn.github.io/theme.park/CSS/themes/plex/organizr-dark.css'></noscript>
```

But no luck. Any help would be appreciated

For anyone wondering how to hide the headers with traefik, this is what I got.

```
http:
  middlewares:
    qbitheaders:
      headers:
        customRequestHeaders:
          X-Webkit-CSP: ""
          content-security-policy: ""
          X-Frame-Options: ""
        customResponseHeaders:
          X-Webkit-CSP: ""
          content-security-policy: ""
          X-Frame-Options: ""
```
