### ISSUE TITLE
TP breaks qBittorrent RSS Tab, once again

### ISSUE THREAD

**Issue by XxAcielxX** [GilbN/theme.park#445]
**Describe the bug**
Using TP with qBittorrent breaks the RSS Tab in the Webui. When pressing the RSS Tab, it does not show. 

**Theme Install Method**
- Install Method: LSIO DOCKER_MOD
- Compose Config
```
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    networks:
      adnio:
        ipv4_address: ${SUBNET}${QBITTORRENT_IP}
    ports:
      - 6885:6881
      - 6885:6881/udp
      - 8080:8080
    environment:
      - PUID=0
      - PGID=0
      - TZ=${TZ}
      - WEBUI_PORT=8080
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:qbittorrent
      - TP_THEME=${THEME}
    volumes:
      - ${APP_CONF}/qbittorrent:/config
      - ${APP_DATA}:/downloads
    restart: unless-stopped
```

**Application Info**
- Version: qBittorrent 4.4.5
- Branch: latest
- Container: linuxserver/qbittorrent

**To Reproduce**
1. Navigate to qBittorrent Webui
2. Click RSS Tab

**Expected behavior**
Clicking the RSS Tab should show the tab.

**Screenshots**
![Screenshot_20221011-155413~2](https://user-images.githubusercontent.com/21063358/195635376-e38e342d-8bb1-4122-bcc2-48dbd2935f3d.jpg)

**Desktop:**
 - OS: Windows 10 Pro x64
 - Browser: Mozilla Firefox
 - Version: 105.0.3

**Smartphone:**
 - Device: OnePlus 5
 - OS: Android 10.0.1
 - Browser: Mozilla Firefox
 - Version: 105.2.0

**Addition Info**
Theme is set to `dracula`.
Disabling TP, RSS Tab shows up perfectly.
I have been this same setup since a year or more, but this issue came back. No idea which update broke it.
