### ISSUE TITLE
nginx no ssl certificate found since last update

### ISSUE THREAD

**Issue by finkdonl** [GilbN/theme.park#482]
**Describe the bug**
nginx no ssl certificate found since last update. theme-park container log:
```nginx: [emerg] no "ssl_certificate" is defined for the "listen ... ssl" directive in /config/nginx/site-confs/default.conf:1
nginx: [emerg] no "ssl_certificate" is defined for the "listen ... ssl" directive in /config/nginx/site-confs/default.conf:1
nginx: [emerg] no "ssl_certificate" is defined for the "listen ... ssl" directive in /config/nginx/site-confs/default.conf:1
nginx: [emerg] no "ssl_certificate" is defined for the "listen ... ssl" directive in /config/nginx/site-confs/default.conf:1
nginx: [emerg] no "ssl_certificate" is defined for the "listen ... ssl" directive in /config/nginx/site-confs/default.conf:1
nginx: [emerg] no "ssl_certificate" is defined for the "listen ... ssl" directive in /config/nginx/site-confs/default.conf:1
```

**Theme Install Method** (Don't skip)
```
version: "2.1"
services:
  theme-park:
    image: ghcr.io/gilbn/theme.park
    container_name: theme-park
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - TP_URLBASE=themepark #optional
    volumes:
      - /home/don/configs/theme-park:/config #optional
    ports:
      - 8888:80
      - 4443:443
    restart: unless-stopped
```
```
version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:sonarr
      - TP_DOMAIN=scully.localdomain:8888
      - TP_SCHEME=http
      - TP_THEME=overseerr
 ```
Themes no longer pulled down by apps:
![Screenshot_20230307_010253](https://user-images.githubusercontent.com/25494428/223334251-57f5ddd3-64ca-4546-9063-f59c55ab1f8c.png)

**Application Info** (Don't skip)
Latest. pulling image in docker-compose

**To Reproduce**
1.  run theme-park with docker compose

**Expected behavior**
No error, themes work
