### ISSUE TITLE
Docker Mods Not Working with LSIO images

### ISSUE THREAD

**Issue by legomind** [GilbN/theme.park#485]
**Describe the bug**
Using the lsio sonarr image, I get the following message when starting the container:
```
[cont-init.d] 98-themepark: executing...
foreground: warning: unable to spawn /var/run/s6/etc/cont-init.d/98-themepark: No such file or directory
```
**Theme Install Method** (Don't skip)

Docker Compose:
```yaml
 sonarr:
    image: linuxserver/sonarr:version-3.0.6.1265
    container_name: sonarr
    restart: 'no'
    ports:
      - '8989:8989'
    volumes:
      - ./sonarr:/config:Z
      - ../downloads:/downloads:z
      - ../shows:/tv:z
      - ../recycle_bin/shows:/recycle_bin:z
    environment:
      PUID: 986
      PGID: 1001
      TZ: America/New_York
      DOCKER_MODS: ghcr.io/gilbn/theme.park:sonarr
      TP_THEME: aquamarine
```

full logs:
```
[mod-init] Attempting to run Docker Modification Logic
[mod-init] Applying gilbn/theme.park:sonarr files to container
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
Sonarr: https://sonarr.tv/donate

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    986
User gid:    1001
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 90-custom-folders: executing...
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 98-themepark: executing...
foreground: warning: unable to spawn /var/run/s6/etc/cont-init.d/98-themepark: No such file or directory
[cont-init.d] 98-themepark: exited 127.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[Info] Bootstrap: Starting Sonarr - /app/sonarr/bin/Sonarr.exe - Version 3.0.6.1265
[Info] AppFolderInfo: Data directory is being overridden to [/config]
[Info] Router: Application mode: Interactive
[Info] MigrationLogger: *** Checking database for required migrations data source=/config/sonarr.db;cache size=-10000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
[Info] MigrationLogger: *** Checking database for required migrations data source=/config/logs.db;cache size=-10000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
[Info] OwinHostController: Listening on the following URLs:
[Info] OwinHostController:   http://*:8989/sonarr/
[Info] OwinHostController:   http://*:8989/
[Info] SonarrBootstrapper: Starting Web Server
[Info] RssSyncService: Starting RSS Sync
[Info] DownloadDecisionMaker: Processing 201 releases
[Info] RssSyncService: RSS Sync Completed. Reports found: 201, Reports grabbed: 0, Reports pending: 1

```
