### ISSUE TITLE
[Sonarr] Custom Filter editor not themed on hover

### ISSUE THREAD

**Issue by rg9400** [gilbN/theme.park#50]
In Mass Editor > Filters > Custom Filters, the background when hovering over existing custom filters is not themed. Current CSS is below -- I can make a PR fixing it, but not sure which color best fits the style guidelines for themepark

```css
.CustomFilter\/customFilter\/zBSMd:hover {
    background-color: #fafbfc;
}
```

![image](https://user-images.githubusercontent.com/39887349/80026594-02871200-84a8-11ea-9651-7f4bb98c859e.png)
