### ISSUE TITLE
Gitea baseTheme requires an update after migrating to 1.20.0

### ISSUE THREAD

**Issue by Crashdummyy** [GilbN/theme.park#500]
**Describe the bug**
After updating Gitea to the most recent version ( 1.20. ) all themes  I tested so far  have to be updated.
The BaseTemplate is probably in need of some new classes

**Application Info** (Don't skip)
[Gitea v.1.20.0](https://github.com/go-gitea/gitea/releases/tag/v1.20.0)

**Screenshots**
![Screenshot from 2023-07-18 23-23-58](https://github.com/GilbN/theme.park/assets/86782769/f0051052-4643-484f-a19c-4d9617e11eed)

![Screenshot from 2023-07-18 23-24-10](https://github.com/GilbN/theme.park/assets/86782769/3750c744-71cb-4776-af56-1c15c0dfdda4)

**Additional context**
For instance the navbar might have introduced a new variable **color-nav-bg**

```css
#navbar {
	display: flex;
	align-items: center;
	background: var(--color-nav-bg);
	border-bottom: 1px solid var(--color-secondary);
	min-height: 52px;
	margin: 0 !important;
}
```

The same issue occurs regarding the footer:

```css
.page-footer {
	display: flex;
	justify-content: space-between;
	background-color: var(--color-footer);
	border-top: 1px solid var(--color-secondary);
	padding: 8px 20px;
}
```

The buttons mightve obtained a new class as well with no background color set whatsoever

```css
.ui.basic.button {
	color: var(--text);
}
```
